spring:
  hadoop:
    fsUri: hdfs://sandbox-hdp.hortonworks.com:8020
    resourceManagerHost: sandbox-hdp.hortonworks.com
  yarn:
    appName: booking
    applicationDir: /app/booking/
    client:
      files:
      - "file:yarn-container-0.1.0.jar"
      - "file:yarn-appmaster-0.1.0.jar"
      launchcontext:
        archiveFile: yarn-appmaster-0.1.0.jar
    appmaster:
      containerCount: 1
      launchcontext:
        archiveFile: yarn-container-0.1.0.jar